name: git-brunch
version: 1.4.2.0
github: "andys8/git-brunch"
license: BSD3
author: "andys8"
maintainer: "andys8@users.noreply.github.com"
copyright: "2020 andys8"

extra-source-files:
  - README.md

synopsis: git checkout command-line tool
category: Git

description: Please see the README on GitHub at <https://github.com/andys8/git-brunch>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - microlens
  - process
  - vector
  - vty
  - optparse-applicative
  - hspec # workaround for language servers

default-extensions:
  - StrictData
  - OverloadedStrings

flags:
  static:
    manual: true
    default: false

ghc-options:
  - -Wall
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  git-brunch:
    main: Main.hs
    source-dirs: app
    when:
      - condition: flag(static)
        then:
          cc-options: -static
          ld-options: -static -pthread
          ghc-options:
            - -with-rtsopts=-N
        else:
          ghc-options: []

tests:
  git-brunch-test:
    main: Spec.hs
    source-dirs:
      - test
      - app
    other-modules:
      - Git
    dependencies:
      - hspec
