name: git-brunch
version: 1.0.6.0
github: "andys8/git-brunch"
license: BSD3
author: "andys8"
maintainer: "andys8@users.noreply.github.com"
copyright: "2020 andys8"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: git checkout command-line tool
category: Git

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/andys8/git-brunch#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - microlens
  - process
  - vector
  - vty

flags:
  static:
    manual: true
    default: false

executables:
  git-brunch:
    main: Main.hs
    source-dirs: app
    when:
      - condition: flag(static)
        then:
          cc-options: -static
          ld-options: -static -pthread
          ghc-options:
            - -static
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
        else:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall

tests:
  git-brunch-test:
    main: Spec.hs
    source-dirs:
      - test
      - app
    other-modules:
      - Git
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
