name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create_release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes

  build_artifact:
    needs: [create_release]
    name: Build Artifact
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: matrix.os  == 'ubuntu-latest'
        uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
            ${{ runner.os }}-stack-
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.6"
          enable-stack: true
          stack-version: "latest"
      - if: matrix.os  == 'ubuntu-latest'
        name: Build binary (linux/dynamic)
        run: stack install --local-bin-path dist
      - if: matrix.os  == 'macos-latest'
        name: Build binary (macos/dynamic)
        run: stack install --local-bin-path dist
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp ./dist/git-brunch ./dist/git-brunch-${{ runner.os }}
          gh release upload ${{ github.ref_name }} ./dist/git-brunch-${{ runner.os }}
